import type { Metadata } from "next";
import "@mantine/core/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
// All Panda CSS -- app styles AND @acme/ui component styles -- comes from this
// one file, generated by the `panda --watch` CLI (see the "dev" script). The
// library ships no CSS of its own; its recipes are emitted here via the
// preset's `staticCss`.
import "styled-system/styles.css";
// Tailwind v4, via @tailwindcss/postcss.
import "./global.css";

export const metadata: Metadata = {
  title: "Panda + Tailwind v4 + Mantine",
  description:
    "Next.js App Router app running Panda, Tailwind v4 and Mantine together",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
