import { Alert } from "@acme/ui";
import { css } from "styled-system/css";
import { VariantSwitcher } from "./variant-switcher";
import { MantineDemo } from "./mantine-demo";

export default function Home() {
  return (
    <main
      className={css({
        minH: "100vh",
        bg: "bg.canvas",
        color: "fg.default",
        display: "grid",
        placeItems: "center",
        p: "6",
      })}
    >
      <div
        className={css({
          display: "flex",
          flexDirection: "column",
          gap: "6",
          w: "full",
          maxW: "md",
        })}
      >
        <h1 className={css({ fontSize: "3xl", fontWeight: "bold" })}>
          Panda + Tailwind v4 + Mantine
        </h1>

        {/* Tailwind v4 utilities */}
        <p className="rounded-lg bg-sky-600 px-4 py-2 text-sm text-white">
          This line is styled with Tailwind v4 utility classes.
        </p>

        {/* Panda slot recipe from the shared preset */}
        <Alert tone="warning" title="Panda slot recipe (from @acme/ui/preset)">
          Generated by Panda via the PostCSS plugin.
        </Alert>

        {/* Mantine component */}
        <MantineDemo />

        <VariantSwitcher />
      </div>
    </main>
  );
}
